#!/usr/bin/env bash 
# Socket Stats Quick 
# - quick test
echo 'Executing:  unset ss'
unset ss
# set -x # enable for debugging
set -e # exit on error
#set -x # show command line
echo 'Executing:  . ss.fun'
. ss.fun
# Not overriding:
echo 'Executing:  ss -tl'
ss -tl
echo 'Executing:  ss -u state closed'
ss -u state closed
# Overriding:
echo 'Executing:  ss ssh'
ss ssh 
echo
echo 'Executing:  ss 22 state established'
ss 22 state established
echo
echo 'Executing:  ss domain -ulpne'
ss domain -ulpne
echo
echo 'Executing:  ss 53 -ul state all'
ss 53 -ul state all
echo

